package io.kmpbits.splash.template

internal object AndroidSplashTemplate {

    /**
     * Generates the splash screen theme XML for `res/values/themes.xml`.
     *
     * Uses the AndroidX SplashScreen API (core-splashscreen).
     * [backgroundColor] is a hex string like "#FF0000".
     * [logoDrawableName] is the drawable resource name without prefix, e.g. "splash_logo".
     */
    fun generateThemes(
        backgroundColor: String,
        logoDrawableName: String? = null,
    ): String {
        val logoItem = if (logoDrawableName != null) {
            """        <item name="windowSplashScreenAnimatedIcon">@drawable/$logoDrawableName</item>"""
        } else ""

        return """<?xml version="1.0" encoding="utf-8"?>
<!-- Note: Theme.App.SplashScreen is auto-generated by kmp-splash during build -->
<resources>
    <style name="Theme.App.SplashScreen" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">$backgroundColor</item>
$logoItem
        <item name="postSplashScreenTheme">@style/Theme.App</item>
    </style>

    <style name="Theme.App" parent="android:Theme.Material.NoActionBar"/>
</resources>"""
    }

    /**
     * Generates the night-mode override for `res/values-night/themes.xml`.
     * Only needed when dark mode uses a different background color.
     */
    fun generateNightThemes(
        backgroundColorNight: String,
        logoDrawableName: String? = null,
    ): String {
        val logoItem = if (logoDrawableName != null) {
            """        <item name="windowSplashScreenAnimatedIcon">@drawable/$logoDrawableName</item>"""
        } else ""

        return """<?xml version="1.0" encoding="utf-8"?>
<!-- Note: Theme.App.SplashScreen is auto-generated by kmp-splash during build -->
<resources>
    <style name="Theme.App.SplashScreen" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">$backgroundColorNight</item>
$logoItem
        <item name="postSplashScreenTheme">@style/Theme.App</item>
    </style>
</resources>"""
    }

    /**
     * Generates `mipmap-anydpi-v26/ic_kmp_app_icon.xml` (also reused verbatim for the round
     * variant — launchers apply their own mask). References the background color and foreground
     * drawable the app icon generation task writes alongside it.
     */
    fun generateAdaptiveIconXml(): String = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/kmp_app_icon_background"/>
    <foreground android:drawable="@mipmap/ic_kmp_app_icon_foreground"/>
</adaptive-icon>"""

    /** Generates `values/kmp_app_icon.xml`, holding the adaptive icon's background color. */
    fun generateAppIconColor(backgroundColor: String): String = """<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="kmp_app_icon_background">$backgroundColor</color>
</resources>"""

    /**
     * Generates a manifest by patching the [baseContent] or creating a new one.
     * It ensures the `<application>` tag has the correct splash theme and registers
     * [KmpSplashInitProvider] so [SplashDefaults] is initialized before any Activity runs.
     * When [iconEnabled] is true, also sets `android:icon`/`android:roundIcon` to the generated
     * app icon, deterministically overwriting any existing value the same way the theme is.
     */
    fun generateManifest(baseContent: String?, iconEnabled: Boolean = false): String {
        val splashTheme = "@style/Theme.App.SplashScreen"
        val themeAttr = "android:theme=\"$splashTheme\""
        val iconAttr = if (iconEnabled) {
            " android:icon=\"@mipmap/ic_kmp_app_icon\" android:roundIcon=\"@mipmap/ic_kmp_app_icon_round\""
        } else ""
        val providerEntry = """        <provider
            android:name="io.kmpbits.splash.KmpSplashInitProvider"
            android:authorities="${'$'}{applicationId}.kmp_splash_init"
            android:exported="false" />"""

        if (baseContent == null) {
            return """<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application $themeAttr$iconAttr>
$providerEntry
    </application>
</manifest>"""
        }

        // Patch theme (and, when enabled, icon) attributes on <application> tag
        val applicationTagRegex = """<application(\s+[^>]*?)(/?)>""".toRegex(RegexOption.DOT_MATCHES_ALL)
        var result = applicationTagRegex.replace(baseContent) { match ->
            val attrs = match.groups[1]?.value ?: ""
            val selfClosing = match.groups[2]?.value ?: ""
            val themeRegex = """android:theme="[^"]*"""".toRegex()

            var newAttrs = if (themeRegex.containsMatchIn(attrs)) {
                themeRegex.replace(attrs, themeAttr)
            } else {
                " $themeAttr$attrs"
            }

            if (iconEnabled) {
                val iconRegex = """\s*android:icon="[^"]*"""".toRegex()
                val roundIconRegex = """\s*android:roundIcon="[^"]*"""".toRegex()
                newAttrs = if (iconRegex.containsMatchIn(newAttrs)) {
                    iconRegex.replace(newAttrs, " android:icon=\"@mipmap/ic_kmp_app_icon\"")
                } else {
                    "$newAttrs android:icon=\"@mipmap/ic_kmp_app_icon\""
                }
                newAttrs = if (roundIconRegex.containsMatchIn(newAttrs)) {
                    roundIconRegex.replace(newAttrs, " android:roundIcon=\"@mipmap/ic_kmp_app_icon_round\"")
                } else {
                    "$newAttrs android:roundIcon=\"@mipmap/ic_kmp_app_icon_round\""
                }
            }

            "<application$newAttrs$selfClosing>"
        }

        // Inject provider only if not already present (guards against in-place re-runs)
        if (!result.contains("io.kmpbits.splash.KmpSplashInitProvider")) {
            val selfClosingRegex = """(<application[^>]*/)>""".toRegex(RegexOption.DOT_MATCHES_ALL)
            result = if (selfClosingRegex.containsMatchIn(result)) {
                selfClosingRegex.replace(result) { match ->
                    "${match.groupValues[1]}>\n$providerEntry\n    </application>"
                }
            } else {
                result.replace("</application>", "$providerEntry\n    </application>")
            }
        }

        return result
    }
}
