package io.kmpbits.splash.template

internal object AndroidSplashTemplate {

    /**
     * Generates the splash screen theme XML for `res/values/themes.xml`.
     *
     * Uses the AndroidX SplashScreen API (core-splashscreen).
     * [backgroundColor] is a hex string like "#FF0000".
     * [logoDrawableName] is the drawable resource name without prefix, e.g. "splash_logo".
     */
    fun generateThemes(
        backgroundColor: String,
        logoDrawableName: String? = null,
    ): String {
        val logoItem = if (logoDrawableName != null) {
            """        <item name="windowSplashScreenAnimatedIcon">@drawable/$logoDrawableName</item>"""
        } else ""

        return """<?xml version="1.0" encoding="utf-8"?>
<!-- Note: Theme.App.SplashScreen is auto-generated by kmp-splash during build -->
<resources>
    <style name="Theme.App.SplashScreen" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">$backgroundColor</item>
$logoItem
        <item name="postSplashScreenTheme">@style/Theme.App</item>
    </style>

    <style name="Theme.App" parent="android:Theme.Material.NoActionBar"/>
</resources>"""
    }

    /**
     * Generates the night-mode override for `res/values-night/themes.xml`.
     * Only needed when dark mode uses a different background color.
     */
    fun generateNightThemes(
        backgroundColorNight: String,
        logoDrawableName: String? = null,
    ): String {
        val logoItem = if (logoDrawableName != null) {
            """        <item name="windowSplashScreenAnimatedIcon">@drawable/$logoDrawableName</item>"""
        } else ""

        return """<?xml version="1.0" encoding="utf-8"?>
<!-- Note: Theme.App.SplashScreen is auto-generated by kmp-splash during build -->
<resources>
    <style name="Theme.App.SplashScreen" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">$backgroundColorNight</item>
$logoItem
        <item name="postSplashScreenTheme">@style/Theme.App</item>
    </style>
</resources>"""
    }

    /**
     * Generates a manifest by patching the [baseContent] or creating a new one.
     * It ensures the `<application>` tag has the correct splash theme.
     */
    fun generateManifest(baseContent: String?): String {
        val splashTheme = "@style/Theme.App.SplashScreen"
        val themeAttr = "android:theme=\"$splashTheme\""
        
        if (baseContent == null) {
            return """<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application $themeAttr />
</manifest>"""
        }

        // Find the <application ... > tag
        val applicationTagRegex = """<application(\s+[^>]*?)(/?)>""".toRegex(RegexOption.DOT_MATCHES_ALL)
        
        return applicationTagRegex.replace(baseContent) { match ->
            val attrs = match.groups[1]?.value ?: ""
            val selfClosing = match.groups[2]?.value ?: ""
            val themeRegex = """android:theme="[^"]*"""".toRegex()
            
            val newAttrs = if (themeRegex.containsMatchIn(attrs)) {
                themeRegex.replace(attrs, themeAttr)
            } else {
                // Prepend theme for visibility
                " $themeAttr$attrs"
            }
            "<application$newAttrs$selfClosing>"
        }
    }
}
