package io.kmpbits.splash

import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class SwiftSplashViewTemplateTest {

    @Test
    fun `header stamp and public SplashView are always present`() {
        val swift = renderSwiftSplashView("SplashBackground", "splash_logo", ExitAnimation.FadeOut(300))
        assertTrue(swift.startsWith("// Generated by kmp-splash — do not edit."))
        assertTrue(swift.contains("public struct KmpSplashView<Content: View>: View"))
        assertTrue(swift.contains("public init(awaitReady: (() async -> Void)? = nil"))
    }

    @Test
    fun `references the background color asset by name`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.None)
        assertTrue(swift.contains("""Color("SplashBackground")"""))
    }

    @Test
    fun `logo centers against the full screen, matching UILaunchScreen, not the safe area`() {
        // UILaunchScreen centers its image against the full screen bounds, ignoring the safe
        // area. An Image without .ignoresSafeArea() centers within the safe area instead, which
        // visibly shifts it whenever the top/bottom insets differ (most current iPhones).
        val swift = renderSwiftSplashView("SplashBackground", "splash_logo", ExitAnimation.None)
        val splashBody = swift.substringAfter("private var splash: some View {")
        assertTrue(splashBody.contains(".ignoresSafeArea()"))
    }

    @Test
    fun `includes the logo image when a name is given`() {
        val swift = renderSwiftSplashView("SplashBackground", "splash_logo", ExitAnimation.None)
        assertTrue(swift.contains("""Image("splash_logo")"""))
    }

    @Test
    fun `omits the logo image when no name is given`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.None)
        assertFalse(swift.contains("Image("))
    }

    @Test
    fun `FadeOut maps to opacity removal transition with duration in seconds`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.FadeOut(300))
        assertTrue(swift.contains("removal: .opacity"))
        assertTrue(swift.contains("withAnimation(.easeInOut(duration: 0.3))"))
    }

    @Test
    fun `SlideUp maps to move top edge`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.SlideUp(400))
        assertTrue(swift.contains("removal: .move(edge: .top)"))
        assertTrue(swift.contains("withAnimation(.easeInOut(duration: 0.4))"))
    }

    @Test
    fun `SlideDown maps to move bottom edge`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.SlideDown(250))
        assertTrue(swift.contains("removal: .move(edge: .bottom)"))
        assertTrue(swift.contains("withAnimation(.easeInOut(duration: 0.25))"))
    }

    @Test
    fun `None uses no animation and identity removal`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.None)
        assertTrue(swift.contains("removal: .identity"))
        assertTrue(swift.contains("withAnimation(nil)"))
    }
}
