package io.kmpbits.splash

import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class SwiftSplashViewTemplateTest {

    @Test
    fun `header stamp and public SplashView are always present`() {
        val swift = renderSwiftSplashView("SplashBackground", "splash_logo", ExitAnimation.FadeOut(300))
        assertTrue(swift.startsWith("// Generated by kmp-splash — do not edit."))
        assertTrue(swift.contains("public struct SplashView<Content: View>: View"))
        assertTrue(swift.contains("public init(isReady: (() async -> Void)? = nil"))
    }

    @Test
    fun `references the background color asset by name`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.None)
        assertTrue(swift.contains("""Color("SplashBackground")"""))
    }

    @Test
    fun `includes the logo image when a name is given`() {
        val swift = renderSwiftSplashView("SplashBackground", "splash_logo", ExitAnimation.None)
        assertTrue(swift.contains("""Image("splash_logo")"""))
    }

    @Test
    fun `omits the logo image when no name is given`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.None)
        assertFalse(swift.contains("Image("))
    }

    @Test
    fun `FadeOut maps to opacity removal transition with duration in seconds`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.FadeOut(300))
        assertTrue(swift.contains("removal: .opacity"))
        assertTrue(swift.contains("withAnimation(.easeInOut(duration: 0.3))"))
    }

    @Test
    fun `SlideUp maps to move top edge`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.SlideUp(400))
        assertTrue(swift.contains("removal: .move(edge: .top)"))
        assertTrue(swift.contains("withAnimation(.easeInOut(duration: 0.4))"))
    }

    @Test
    fun `SlideDown maps to move bottom edge`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.SlideDown(250))
        assertTrue(swift.contains("removal: .move(edge: .bottom)"))
        assertTrue(swift.contains("withAnimation(.easeInOut(duration: 0.25))"))
    }

    @Test
    fun `None uses no animation and identity removal`() {
        val swift = renderSwiftSplashView("SplashBackground", null, ExitAnimation.None)
        assertTrue(swift.contains("removal: .identity"))
        assertTrue(swift.contains("withAnimation(nil)"))
    }
}
