// Generated by kmp-splash — do not edit manually
package io.kmpbits.splash

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.graphics.Color
import kmp_splash.sample.composeapp.generated.resources.Res
import kmp_splash.sample.composeapp.generated.resources.logo
import org.jetbrains.compose.resources.painterResource
import androidx.compose.ui.graphics.painter.Painter

class SplashDefaults(
    val backgroundColor: Color,
    val logoPainter: (@Composable () -> Painter?)? = null
)

object SplashConfig {
    @Composable
    operator fun invoke(
        isReady: suspend () -> Boolean,
        onFinished: () -> Unit,
    ) {
        val backgroundColor = if (isSystemInDarkTheme()) Color(0xFF1A1A2E) else Color(0xFFFFFFFF)
        val logoPainter = @Composable {
        painterResource(Res.drawable.logo)
    }

        CompositionLocalProvider(
            LocalSplashBackgroundColor provides backgroundColor,
            LocalSplashLogoPainter provides logoPainter
        ) {
            SplashScreen(
                isReady = isReady,
                onFinished = onFinished,
            )
        }
    }
}
