// Generated by kmp-splash — do not edit manually
package io.kmpbits.splash

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import kmp_splash.sample.composeapp.generated.resources.Res
import kmp_splash.sample.composeapp.generated.resources.logo
import org.jetbrains.compose.resources.painterResource

object SplashConfig {

    init {
        SplashDefaults.backgroundColor = Color(0xFF1A1A2E)
        SplashDefaults.logoPainter = @androidx.compose.runtime.Composable {
            painterResource(Res.drawable.logo)
        }
    }

    @Composable
    operator fun invoke(
        isReady: suspend () -> Boolean,
        onFinished: () -> Unit,
    ) {
        SplashScreen(isReady = isReady, onFinished = onFinished)
    }
}
