package io.kmpbits.splash

import java.util.Locale

/** SwiftUI removal transition + `withAnimation(...)` argument for a given [ExitAnimation]. */
private data class SwiftExit(val removalTransition: String, val animation: String)

private fun ExitAnimation.toSwiftExit(): SwiftExit {
    fun seconds(ms: Int) = "%.3f".format(Locale.US, ms / 1000.0).trimEnd('0').trimEnd('.')
    return when (this) {
        is ExitAnimation.None -> SwiftExit(".identity", "nil")
        is ExitAnimation.FadeOut -> SwiftExit(".opacity", ".easeInOut(duration: ${seconds(durationMs)})")
        is ExitAnimation.SlideUp -> SwiftExit(".move(edge: .top)", ".easeInOut(duration: ${seconds(durationMs)})")
        is ExitAnimation.SlideDown -> SwiftExit(".move(edge: .bottom)", ".easeInOut(duration: ${seconds(durationMs)})")
    }
}

/**
 * Renders the full contents of `KmpSplashView.swift`. Pure — no filesystem, no Gradle — so the
 * output is unit-testable directly.
 *
 * @param backgroundColorAssetName named color in the generated `Assets.xcassets` (always
 *   `"SplashBackground"`); referenced rather than baked so the generated dark-mode color is reused.
 * @param logoImageAssetName imageset name in `Assets.xcassets`, or `null` for a solid-color splash.
 * @param exitAnimation the DSL exit animation, mapped to a SwiftUI removal transition.
 */
internal fun renderSwiftSplashView(
    backgroundColorAssetName: String,
    logoImageAssetName: String?,
    exitAnimation: ExitAnimation,
): String {
    val exit = exitAnimation.toSwiftExit()
    val logoLine = if (logoImageAssetName != null) {
        "\n            Image(\"$logoImageAssetName\")"
    } else ""

    return """// Generated by kmp-splash — do not edit. Regenerated on every Gradle sync.
import SwiftUI

/// Holds the native launch screen until `awaitReady` returns, then animates it away.
///
/// `awaitReady` is called once and awaited to completion — it is not a condition that gets
/// re-checked. If your readiness signal is a value that changes over time (e.g. a `@Published`
/// property on an `ObservableObject`), `awaitReady` must itself suspend until that value settles,
/// for example by awaiting its Combine `.values` async sequence — see the README's "SwiftUI
/// (native iOS UI)" section for a full example.
///
/// ```swift
/// KmpSplashView(awaitReady: {
///     await AppGraph.shared.warmUp()
/// }, content: {
///     ContentView()
/// })
/// ```
public struct KmpSplashView<Content: View>: View {
    private let awaitReady: (() async -> Void)?
    private let content: () -> Content

    public init(awaitReady: (() async -> Void)? = nil,
                @ViewBuilder content: @escaping () -> Content) {
        self.awaitReady = awaitReady
        self.content = content
    }

    @State private var showSplash = true

    public var body: some View {
        ZStack {
            content()
            if showSplash {
                splash
                    .transition(.asymmetric(insertion: .identity, removal: ${exit.removalTransition}))
                    .zIndex(1)
            }
        }
        .task {
            await awaitReady?()
            withAnimation(${exit.animation}) { showSplash = false }
        }
    }

    private var splash: some View {
        // .ignoresSafeArea() on the whole ZStack, not just the background: UILaunchScreen centers
        // its image against the full screen bounds, ignoring the safe area entirely (it predates
        // the safe-area API). Centering the logo within the safe area instead — which is what an
        // Image gets by default — visibly shifts it on any device where the top inset (Dynamic
        // Island/notch) differs from the bottom one (home indicator), i.e. most current iPhones.
        ZStack {
            Color("$backgroundColorAssetName")$logoLine
        }
        .ignoresSafeArea()
    }
}
"""
}
