package io.kmpbits.splash

import java.util.Locale

/** SwiftUI removal transition + `withAnimation(...)` argument for a given [ExitAnimation]. */
private data class SwiftExit(val removalTransition: String, val animation: String)

private fun ExitAnimation.toSwiftExit(): SwiftExit {
    fun seconds(ms: Int) = "%.3f".format(Locale.US, ms / 1000.0).trimEnd('0').trimEnd('.')
    return when (this) {
        is ExitAnimation.None -> SwiftExit(".identity", "nil")
        is ExitAnimation.FadeOut -> SwiftExit(".opacity", ".easeInOut(duration: ${seconds(durationMs)})")
        is ExitAnimation.SlideUp -> SwiftExit(".move(edge: .top)", ".easeInOut(duration: ${seconds(durationMs)})")
        is ExitAnimation.SlideDown -> SwiftExit(".move(edge: .bottom)", ".easeInOut(duration: ${seconds(durationMs)})")
    }
}

/**
 * Renders the full contents of `KmpSplashView.swift`. Pure — no filesystem, no Gradle — so the
 * output is unit-testable directly.
 *
 * @param backgroundColorAssetName named color in the generated `Assets.xcassets` (always
 *   `"SplashBackground"`); referenced rather than baked so the generated dark-mode color is reused.
 * @param logoImageAssetName imageset name in `Assets.xcassets`, or `null` for a solid-color splash.
 * @param exitAnimation the DSL exit animation, mapped to a SwiftUI removal transition.
 */
internal fun renderSwiftSplashView(
    backgroundColorAssetName: String,
    logoImageAssetName: String?,
    exitAnimation: ExitAnimation,
): String {
    val exit = exitAnimation.toSwiftExit()
    val logoLine = if (logoImageAssetName != null) {
        "\n            Image(\"$logoImageAssetName\")"
    } else ""

    return """// Generated by kmp-splash — do not edit. Regenerated on every Gradle sync.
import SwiftUI

/// Holds the native launch screen until `isReady` completes, then animates it away.
///
/// ```swift
/// SplashView(isReady: { await AppGraph.shared.warmUp() }) {
///     ContentView()
/// }
/// ```
public struct SplashView<Content: View>: View {
    private let isReady: (() async -> Void)?
    private let content: () -> Content

    public init(isReady: (() async -> Void)? = nil,
                @ViewBuilder content: @escaping () -> Content) {
        self.isReady = isReady
        self.content = content
    }

    @State private var showSplash = true

    public var body: some View {
        ZStack {
            content()
            if showSplash {
                splash
                    .transition(.asymmetric(insertion: .identity, removal: ${exit.removalTransition}))
                    .zIndex(1)
            }
        }
        .task {
            await isReady?()
            withAnimation(${exit.animation}) { showSplash = false }
        }
    }

    private var splash: some View {
        ZStack {
            Color("$backgroundColorAssetName").ignoresSafeArea()$logoLine
        }
    }
}
"""
}
