package io.kmpbits.splash.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

abstract class GenerateLaunchScreenTask : DefaultTask() {

    @get:Input
    @get:Optional
    abstract val backgroundColor: Property<String>

    @get:Input
    @get:Optional
    abstract val logoResourceName: Property<String>

    /** Raw configured path — tracked as @Input so incremental builds re-run on path changes. */
    @get:Input
    @get:Optional
    abstract val logoFilePath: Property<String>

    /** Compose resources package of the consuming module, e.g. com_example.myapp.generated.resources */
    @get:Input
    @get:Optional
    abstract val resourcePackage: Property<String>

    /** Resolved file handle — @Internal so Gradle skips its own (unfriendly) validation. */
    @get:Internal
    abstract val logoSourceFile: RegularFileProperty

    /**
     * Assets.xcassets directory inside the iOS project folder.
     * Contains the SplashBackground named color used by UILaunchScreen.
     */
    @get:OutputDirectory
    abstract val xcassetsDir: DirectoryProperty

    @get:OutputFile
    abstract val splashConfigFile: RegularFileProperty

    @get:OutputFile
    abstract val pbxprojFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val resolvedColor = resolveBackgroundColor()
        val resolvedLogoName = copyLogoAsset()

        generateColorAsset(resolvedColor)
        patchInfoPlist(xcassetsDir.asFile.get().parentFile.resolve("Info.plist"), resolvedLogoName)
        patchProjectPbxproj()
        generateSplashConfig(resolvedColor, resolvedLogoName)
    }

    private fun copyLogoAsset(): String? {
        val configuredPath = logoFilePath.orNull ?: return null
        val src = logoSourceFile.asFile.get()
        if (!src.exists()) {
            throw GradleException(
                "KmpSplash: logoFile '$configuredPath' was not found at ${src.absolutePath}.\n" +
                "  The path must be relative to the module directory (e.g. 'src/commonMain/composeResources/drawable/logo.png')."
            )
        }
        val name = logoResourceName.get()
        val imageset = xcassetsDir.asFile.get().resolve("$name.imageset")
        imageset.mkdirs()
        src.copyTo(imageset.resolve(src.name), overwrite = true)
        imageset.resolve("Contents.json").writeText(logoContentsJson(src.name))
        return name
    }

    private fun resolveBackgroundColor(): String {
        val color = backgroundColor.orNull
        if (color == null) {
            logger.warn(
                "KmpSplash: backgroundColor is not set. Falling back to #FFFFFF."
            )
            return "#FFFFFF"
        }
        return color
    }

    private fun generateColorAsset(hexColor: String) {
        val (r, g, b) = parseHexColor(hexColor)
        val xcassets = xcassetsDir.asFile.get()
        xcassets.mkdirs()
        xcassets.resolve("Contents.json").writeText(
            """{"info":{"author":"kmp-splash","version":1}}"""
        )
        val colorset = xcassets.resolve("SplashBackground.colorset")
        colorset.mkdirs()
        colorset.resolve("Contents.json").writeText("""
{
  "colors": [
    {
      "color": {
        "color-space": "srgb",
        "components": { "alpha": "1.000", "red": "$r", "green": "$g", "blue": "$b" }
      },
      "idiom": "universal"
    }
  ],
  "info": { "author": "kmp-splash", "version": 1 }
}""".trimIndent())
        val appiconset = xcassets.resolve("AppIcon.appiconset")
        if (!appiconset.exists()) {
            appiconset.mkdirs()
            appiconset.resolve("Contents.json").writeText("""{"images":[],"info":{"author":"kmp-splash","version":1}}""")
        }
        logger.lifecycle("KmpSplash: wrote SplashBackground color asset")
    }

    private fun generateSplashConfig(hexColor: String, logoName: String?) {
        val argbHex = "FF${hexColor.trimStart('#').uppercase()}"
        val configFile = splashConfigFile.asFile.get()
        configFile.parentFile.mkdirs()

        val resPkg = resourcePackage.orNull
        val logoImports = if (logoName != null && resPkg != null) """
import $resPkg.Res
import $resPkg.$logoName
import org.jetbrains.compose.resources.painterResource
import androidx.compose.ui.graphics.painter.Painter""" else ""

        val logoPainterValue = if (logoName != null && resPkg != null) """@Composable {
            painterResource(Res.drawable.$logoName)
        }""" else "null"

        configFile.writeText(
            """// Generated by kmp-splash — do not edit manually
package io.kmpbits.splash

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color$logoImports

object SplashDefaults {
    val backgroundColor = Color(0x$argbHex)
    val logoPainter: (@Composable () -> Painter?)? = $logoPainterValue
}

object SplashConfig {
    @Composable
    operator fun invoke(
        isReady: suspend () -> Boolean,
        onFinished: () -> Unit,
    ) {
        SplashScreen(
            isReady = isReady,
            onFinished = onFinished,
            backgroundColor = SplashDefaults.backgroundColor,
            logoPainter = SplashDefaults.logoPainter
        )
    }
}
"""
        )
        logger.lifecycle("KmpSplash: wrote ${configFile.absolutePath}")
    }

    private fun patchInfoPlist(plist: java.io.File, logoName: String?) {
        if (!plist.exists()) {
            logger.warn("KmpSplash: Info.plist not found — skipping")
            return
        }
        // Remove stale keys (plutil exits non-zero if key absent — that's fine)
        runPlutil("-remove", "UILaunchStoryboardName", plist.absolutePath)
        runPlutil("-remove", "UILaunchScreen", plist.absolutePath)
        // Insert UILaunchScreen dict
        runPlutil("-insert", "UILaunchScreen", "-dictionary", plist.absolutePath)
        runPlutil("-insert", "UILaunchScreen.UIColorName", "-string", "SplashBackground", plist.absolutePath)
        if (logoName != null) {
            runPlutil("-insert", "UILaunchScreen.UIImageName", "-string", logoName, plist.absolutePath)
        }
        logger.lifecycle("KmpSplash: patched Info.plist with UILaunchScreen")
    }

    private fun runPlutil(vararg args: String) {
        val process = ProcessBuilder("plutil", *args)
            .redirectErrorStream(true)
            .start()
        process.waitFor()
    }

    private fun patchProjectPbxproj() {
        val pbxproj = pbxprojFile.asFile.get()
        if (!pbxproj.exists()) return

        var text = pbxproj.readText()

        val xcassetsFileRefUuid  = "B310DBF02A7B8C1B00943F69"
        val xcassetsBuildFileUuid = "B310DBF12A7B8C1C00943F69"
        val resourcesUuid        = "B310DBE22A7B8C1C00943F69"

        // Remove stale storyboard entries if present
        val storyboardBuildFile = "B310DBE02A7B8C1C00943F69"
        val storyboardFileRef   = "B310DBE12A7B8C1B00943F69"
        text = text.lines()
            .filter { line ->
                !line.contains(storyboardBuildFile) &&
                !line.contains(storyboardFileRef) &&
                !line.contains("LaunchScreen.storyboard")
            }
            .joinToString("\n")

        val hasXcassetsRef = text.contains(xcassetsFileRefUuid)
        val hasXcassetsInResources = text.contains("$xcassetsBuildFileUuid /* Assets.xcassets in Resources */,")

        if (hasXcassetsRef && hasXcassetsInResources) {
            logger.lifecycle("KmpSplash: project.pbxproj already references Assets.xcassets")
            pbxproj.writeText(text)
            return
        }

        // 1. PBXBuildFile
        if (!text.contains(xcassetsBuildFileUuid)) {
            text = text.replace(
                "/* End PBXBuildFile section */",
                "\t\t$xcassetsBuildFileUuid /* Assets.xcassets in Resources */ = " +
                "{isa = PBXBuildFile; fileRef = $xcassetsFileRefUuid /* Assets.xcassets */; };\n" +
                "/* End PBXBuildFile section */"
            )
        }

        // 2. PBXFileReference
        if (!hasXcassetsRef) {
            text = text.replace(
                "/* End PBXFileReference section */",
                "\t\t$xcassetsFileRefUuid /* Assets.xcassets */ = " +
                "{isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; " +
                "path = Assets.xcassets; sourceTree = \"<group>\"; };\n" +
                "/* End PBXFileReference section */"
            )
        }

        // 3. Group entry after Info.plist
        if (!text.contains("$xcassetsFileRefUuid /* Assets.xcassets */,")) {
            text = text.replace(
                "B310DBB52A7B8C1B00943F69 /* Info.plist */,",
                "B310DBB52A7B8C1B00943F69 /* Info.plist */,\n\t\t\t\t$xcassetsFileRefUuid /* Assets.xcassets */,"
            )
        }

        // 4. Ensure PBXResourcesBuildPhase exists
        if (!text.contains("PBXResourcesBuildPhase")) {
            val phase = """
/* Begin PBXResourcesBuildPhase section */
		$resourcesUuid /* Resources */ = {
			isa = PBXResourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				$xcassetsBuildFileUuid /* Assets.xcassets in Resources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXResourcesBuildPhase section */

"""
            text = text.replace(
                "/* Begin PBXSourcesBuildPhase section */",
                phase + "/* Begin PBXSourcesBuildPhase section */"
            )
        } else if (!hasXcassetsInResources) {
            // Add xcassets to existing Resources phase files list
            text = text.replace(
                "$resourcesUuid /* Resources */ = {\n\t\t\tisa = PBXResourcesBuildPhase;\n\t\t\tbuildActionMask = 2147483647;\n\t\t\tfiles = (\n\t\t\t);",
                "$resourcesUuid /* Resources */ = {\n\t\t\tisa = PBXResourcesBuildPhase;\n\t\t\tbuildActionMask = 2147483647;\n\t\t\tfiles = (\n\t\t\t\t$xcassetsBuildFileUuid /* Assets.xcassets in Resources */,\n\t\t\t);"
            )
        }

        // 5. Ensure Resources phase is in target buildPhases
        if (!text.contains("$resourcesUuid /* Resources */,")) {
            text = text.replace(
                "B310DBCA2A7B8C1C00943F69 /* Embed Frameworks */,",
                "$resourcesUuid /* Resources */,\n\t\t\t\tB310DBCA2A7B8C1C00943F69 /* Embed Frameworks */,"
            )
        }

        pbxproj.writeText(text)
        logger.lifecycle("KmpSplash: patched project.pbxproj to reference Assets.xcassets")
    }

    private fun parseHexColor(hex: String): Triple<String, String, String> {
        val clean = hex.trimStart('#').also {
            require(it.length == 6) { "backgroundColor must be #RRGGBB, got: $hex" }
        }
        fun channel(start: Int) = (clean.substring(start, start + 2).toInt(16) / 255.0).toString()
        return Triple(channel(0), channel(2), channel(4))
    }

    private fun logoContentsJson(filename: String) = """{
  "images": [
    { "idiom": "universal", "filename": "$filename", "scale": "1x" },
    { "idiom": "universal", "filename": "$filename", "scale": "2x" },
    { "idiom": "universal", "filename": "$filename", "scale": "3x" }
  ],
  "info": { "author": "kmp-splash", "version": 1 }
}"""
}
